# Syntax highlighting
markdown:                 redcarpet
highlighter:              pygments

# Permalinks
permalink:                /:title
relative_permalinks:      true

# Setup
timezone:                 'Europe/Brussels'
locale:                   'en_us'
name:                     'Aja''S Artwork'
title:                    'Aja''S Artwork'
tagline:                  'Art is just meaningless'
description:              'Hello, this is my website'
url:                      'https://armongo.github.io'
rss:                      '/feed.xml'
baseurl:                  '/'
baseurl_posts_img:        '/assets/images/posts/'
baseurl_featured_img:     '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts:      '/assets/javascripts/'
icon:                     '/assets/img/icon.png'

author:
  name:                   'Yameng'
  url:                    'https://armongo.github.io'
  # facebook:              username
  # twitter:               username
  # …

# Server
destination:              ./_site
exclude:
  - ".editorconfig"
  - ".gitignore"
  - "CNAME"
  - "package.json"
  - "README.md"
  - "sass"
  - "haml"
  - "Gemfile"
  - "Gemfile.lock"
  - "Dockerfile"
  - "build.py"
port:                     9001

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
