# At the very top of your workflow file:
permissions:
  contents: write          # allow git push of files
  pages: write             # allow Pages deployment
  id-token: write          # only needed if you use OIDC

name: Build & Deploy Jekyll site
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0           # ensure full history for Actions GH Pages
          persist-credentials: true  # preserves GITHUB_TOKEN for the push

      - name: Build Docker image
        run: docker build -t mickey:latest .

      - name: Run build inside container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/srv/jekyll" \
            mickey:latest

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
